// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sparse_action
Eigen::VectorXd sparse_action(const Eigen::SparseMatrix<double, Eigen::RowMajor>& A, const Eigen::VectorXd& v, const double& t, const int& krylov_dim, const double& tol);
RcppExport SEXP _pathintegrateR_sparse_action(SEXP ASEXP, SEXP vSEXP, SEXP tSEXP, SEXP krylov_dimSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double, Eigen::RowMajor>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const double& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const int& >::type krylov_dim(krylov_dimSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_action(A, v, t, krylov_dim, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pathintegrateR_sparse_action", (DL_FUNC) &_pathintegrateR_sparse_action, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pathintegrateR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
